name: Deploy Server on Exclude

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on Exclude
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 210.79.129.156
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd home/ubuntu/depoyement-test
            git pull origin main
            npm install
            npm start